### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by erizocosmico**
Just finished the spanish translation of this mod.

### CODE REVIEW

**Comment by Pico** [comment]
Thanks for translation.
I will not merge it until I finish next version.

**Comment by erizocosmico** [comment]
Okay, just let me know if there are changes in the language files in the next version so I can update the translation.

**Comment by phpbb-es** [comment]
Spanish Translation??? Sure???
The translation is performed from February 2013
https://www.phpbb.com/community/viewtopic.php?f=70&t=2147118&p=13248595#p13248595

**Comment by erizocosmico** [comment]
Oh, sorry, I didn't realise that there was a translation :P

**Comment by phpbb-es** [comment]
No problem ;)

**Comment by Pico** [comment]
Ok. Language files are done. You can check them and prepere translation. I'm goint to release 0.7.0 on 31st July.
Also prepere xml file like polish one. Without it, I will not merge it.

**Comment by phpbb-es** [comment]
No problem Pico ;)

**Comment by phpbb-es** [comment]
Package Spanish ready.

**Comment by Pico** [comment]
I didn't see any diffrence. There are some new lines in lang files. Moreover some lang variables are removed.
Have a look at branch lang files.

**Comment by phpbb-es** [comment]
This is the new version Pico.

2013/7/28 Pico88 notifications@github.com

> I didn't see any diffrence. There are some new lines in lang files.
> Moreover some lang variables are removed.
> Have a look at branch lang files.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Pico88/phpBB-Reputation-System/pull/26#issuecomment-21688367
> .

## 

_Raúl Arroyo Monzo.
Webmaster:
http://www.phpbb-es.com_ - *http://www.phpbbmods.es -
http://www.icyphoenix.es
http://www.thekuka.net - http://www.raularroyomonzo.es
Administrador, Jefe del equipo de traductores:
http://www.icyphoenix.com
International Support Team y Traductor:
http://www.phpbb.com
*

**Comment by Pico** [comment]
There is no xml file and translation is not up-to-date. Please fix that.

**Comment by phpbb-es** [comment]
I do not understand what the xml file, I assume you mean to include the *
Spanish.xml\* in the _/__contrib/_ folder.

Merged files included by you, made by mvader, my translation (by ThE KuKa)
was provided to phpBB forums directly Pico.
https://www.phpbb.com/community/viewtopic.php?f=70&t=2147118&p=13248595#p13248595

Attach new revision, github is not good use for me, sorry...

Regards.

2013/7/29 Pico88 notifications@github.com

> There is no xml file and translation is not up-to-date. Please fix that.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Pico88/phpBB-Reputation-System/pull/26#issuecomment-21702705
> .

## 

_Raúl Arroyo Monzo.
Webmaster:
http://www.phpbb-es.com_ - *http://www.phpbbmods.es -
http://www.icyphoenix.es
http://www.thekuka.net - http://www.raularroyomonzo.es
Administrador, Jefe del equipo de traductores:
http://www.icyphoenix.com
International Support Team y Traductor:
http://www.phpbb.com
*

**Pull request merged**
